spring.application.name=eureka-server
server.port=8761

# Eureka server configuration to prevent it from registering with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

# Disable Spring Cloud compatibility verifier check
spring.cloud.compatibility-verifier.enabled=false
