package com.mediahub.iam.entity;

import com.mediahub.iam.enums.AuditAction;
import jakarta.persistence.*;

import java.time.LocalDateTime;

// JPA entity mapped to the "audit_log" table; each instance is one audit trail record.
// Captures who did what to which entity, including before/after values, for tracking changes.
@Entity
@Table(name = "audit_log")
public class AuditLog {

    // Primary key for the audit record; auto-generated by the database (IDENTITY/auto-increment).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long auditId;

    // Many-to-one link to the User who performed the action, joined via the "userId" column.
    // Required (nullable = false), so every audit entry must reference a user.
    @ManyToOne
    @JoinColumn(name = "userId", nullable = false)
    private User user;

    // The action performed (from the AuditAction enum), stored as its String name in the DB.
    // Required column, so every record must specify what kind of action occurred.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AuditAction action;

    // The type/category of the affected entity (e.g. "User", "Role"); required, max 60 chars.
    @Column(nullable = false, length = 60)
    private String entityType;

    // The id of the specific affected entity, stored as a String; required, max 60 chars.
    @Column(nullable = false, length = 60)
    private String entityId;

    // Snapshot of the entity's state before the change, stored as a JSON string (nullable).
    @Column(columnDefinition = "JSON")
    private String oldValue;

    // Snapshot of the entity's state after the change, stored as a JSON string (nullable).
    @Column(columnDefinition = "JSON")
    private String newValue;

    // The IP address from which the action originated; optional, sized to hold IPv4/IPv6 (45 chars).
    @Column(length = 45)
    private String ipAddress;

    // Timestamp of when the record was created; required and never updated after insert (updatable = false).
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // JPA lifecycle callback run just before the entity is first persisted.
    // Stamps "createdAt" with the current time so the creation timestamp is set automatically.
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    // Getters and setters for each field, used by JPA and application code to read/write values.
    // Note "createdAt" is read-only (getter only) since it is set automatically and never changed.
    public Long getAuditId() { return auditId; }
    public void setAuditId(Long auditId) { this.auditId = auditId; }
    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }
    public AuditAction getAction() { return action; }
    public void setAction(AuditAction action) { this.action = action; }
    public String getEntityType() { return entityType; }
    public void setEntityType(String entityType) { this.entityType = entityType; }
    public String getEntityId() { return entityId; }
    public void setEntityId(String entityId) { this.entityId = entityId; }
    public String getOldValue() { return oldValue; }
    public void setOldValue(String oldValue) { this.oldValue = oldValue; }
    public String getNewValue() { return newValue; }
    public void setNewValue(String newValue) { this.newValue = newValue; }
    public String getIpAddress() { return ipAddress; }
    public void setIpAddress(String ipAddress) { this.ipAddress = ipAddress; }
    public LocalDateTime getCreatedAt() { return createdAt; }
}