package com.mediahub.iam.entity;

import jakarta.persistence.*;

// JPA entity mapped to the "permission" table; each instance is one permission record.
// Represents a single grantable permission that can be assigned to roles.
@Entity
@Table(name = "permission")
public class Permission {

    // Primary key for the permission; auto-generated by the database (IDENTITY/auto-increment).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long permissionId;

    // The permission's name/type (e.g. "READ_USER"); required, must be unique, max 100 chars.
    @Column(nullable = false, unique = true, length = 100)
    private String permissionType;

    // Getters and setters for each field, used by JPA and application code to read/write values.
    public Long getPermissionId() { return permissionId; }
    public void setPermissionId(Long permissionId) { this.permissionId = permissionId; }
    public String getPermissionType() { return permissionType; }
    public void setPermissionType(String permissionType) { this.permissionType = permissionType; }
}