package com.mediahub.iam.entity;

import jakarta.persistence.*;

// JPA entity mapped to the "role_permission" join table; each row links one role to one permission.
// The unique constraint on (roleId, permissionId) prevents the same permission being assigned to a role twice.
@Entity
@Table(name = "role_permission",
    uniqueConstraints = @UniqueConstraint(
        columnNames = {"roleId", "permissionId"}
    )
)
public class RolePermission {

    // Primary key for the join record; auto-generated by the database (IDENTITY/auto-increment).
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long rolePermissionId;

    // Many-to-one link to the Role side of the mapping, joined via the "roleId" column (required).
    @ManyToOne
    @JoinColumn(name = "roleId", nullable = false)
    private Role role;

    // Many-to-one link to the Permission side of the mapping, joined via the "permissionId" column (required).
    @ManyToOne
    @JoinColumn(name = "permissionId", nullable = false)
    private Permission permission;

    // Getters and setters for each field, used by JPA and application code to read/write the linked entities.
    public Long getRolePermissionId() { return rolePermissionId; }
    public void setRolePermissionId(Long rolePermissionId) { this.rolePermissionId = rolePermissionId; }
    public Role getRole() { return role; }
    public void setRole(Role role) { this.role = role; }
    public Permission getPermission() { return permission; }
    public void setPermission(Permission permission) { this.permission = permission; }
}